"""add roadmaps milestones and tasks

Revision ID: 469f9f8c7dee
Revises: df84b7422db9
Create Date: 2026-10-03 23:02:39.597507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '469f9f8c7dee'
down_revision: Union[str, Sequence[str], None] = 'df84b7422db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'completed', 'paused', 'cancelled', name='goal_status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_goal_id'), 'roadmaps', ['goal_id'], unique=False)
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_milestone_position'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'position', name='uq_milestone_position')
    )
    op.create_index(op.f('ix_milestones_roadmap_id'), 'milestones', ['roadmap_id'], unique=False)
    op.create_table('learning_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='task_status'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_task_position'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['learning_topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id', 'position', name='uq_task_position')
    )
    op.create_index(op.f('ix_learning_tasks_milestone_id'), 'learning_tasks', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_learning_tasks_resource_id'), 'learning_tasks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_learning_tasks_topic_id'), 'learning_tasks', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_tasks_topic_id'), table_name='learning_tasks')
    op.drop_index(op.f('ix_learning_tasks_resource_id'), table_name='learning_tasks')
    op.drop_index(op.f('ix_learning_tasks_milestone_id'), table_name='learning_tasks')
    op.drop_table('learning_tasks')
    op.drop_index(op.f('ix_milestones_roadmap_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_goal_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    sa.Enum(name='task_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
