"""add goal skill requirements and notifications

Revision ID: bea5be187306
Revises: d89ac8d30fd0
Create Date: 2026-10-03 23:09:06.879723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea5be187306'
down_revision: Union[str, Sequence[str], None] = 'd89ac8d30fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('goal_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_proficiency', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint("required_proficiency IN ('beginner', 'intermediate', 'advanced', 'expert')", name='ck_goal_skill_proficiency'),
    sa.CheckConstraint('position >= 0', name='ck_goal_skill_position'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'position', name='uq_goal_skill_position'),
    sa.UniqueConstraint('goal_id', 'skill_id', name='uq_goal_skill')
    )
    op.create_index(op.f('ix_goal_skills_goal_id'), 'goal_skills', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_skills_skill_id'), 'goal_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_skills_skill_id'), table_name='goal_skills')
    op.drop_index(op.f('ix_goal_skills_goal_id'), table_name='goal_skills')
    op.drop_table('goal_skills')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
